name: image_generator_bloc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.7.0-209.1.beta <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  dio: ^5.7.0
  lottie: ^3.3.1
  animated_text_kit: ^4.2.2
  dotted_border: ^2.1.0
  image_picker: ^1.1.2
  # image_gallery_saver: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/.env
    - assets/images/
    - assets/animations/
